# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/bin/cmake

# The command to remove a file.
RM = /nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gavin4d/programming/Multiscale-Curvature-Analysis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gavin4d/programming/Multiscale-Curvature-Analysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gavin4d/programming/Multiscale-Curvature-Analysis/CMakeFiles /home/gavin4d/programming/Multiscale-Curvature-Analysis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gavin4d/programming/Multiscale-Curvature-Analysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named analysis

# Build rule for target.
analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analysis
.PHONY : analysis

# fast build rule for target.
analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/build
.PHONY : analysis/fast

#=============================================================================
# Target rules for targets named dataContainer

# Build rule for target.
dataContainer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dataContainer
.PHONY : dataContainer

# fast build rule for target.
dataContainer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dataContainer.dir/build.make CMakeFiles/dataContainer.dir/build
.PHONY : dataContainer/fast

#=============================================================================
# Target rules for targets named fileConvert

# Build rule for target.
fileConvert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fileConvert
.PHONY : fileConvert

# fast build rule for target.
fileConvert/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fileConvert.dir/build.make CMakeFiles/fileConvert.dir/build
.PHONY : fileConvert/fast

#=============================================================================
# Target rules for targets named gui

# Build rule for target.
gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui
.PHONY : gui

# fast build rule for target.
gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/build
.PHONY : gui/fast

analysis.o: analysis.cpp.o
.PHONY : analysis.o

# target to build an object file
analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/analysis.cpp.o
.PHONY : analysis.cpp.o

analysis.i: analysis.cpp.i
.PHONY : analysis.i

# target to preprocess a source file
analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/analysis.cpp.i
.PHONY : analysis.cpp.i

analysis.s: analysis.cpp.s
.PHONY : analysis.s

# target to generate assembly for a file
analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/analysis.cpp.s
.PHONY : analysis.cpp.s

dataContainer.o: dataContainer.cpp.o
.PHONY : dataContainer.o

# target to build an object file
dataContainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dataContainer.dir/build.make CMakeFiles/dataContainer.dir/dataContainer.cpp.o
.PHONY : dataContainer.cpp.o

dataContainer.i: dataContainer.cpp.i
.PHONY : dataContainer.i

# target to preprocess a source file
dataContainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dataContainer.dir/build.make CMakeFiles/dataContainer.dir/dataContainer.cpp.i
.PHONY : dataContainer.cpp.i

dataContainer.s: dataContainer.cpp.s
.PHONY : dataContainer.s

# target to generate assembly for a file
dataContainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dataContainer.dir/build.make CMakeFiles/dataContainer.dir/dataContainer.cpp.s
.PHONY : dataContainer.cpp.s

fileConvert.o: fileConvert.cpp.o
.PHONY : fileConvert.o

# target to build an object file
fileConvert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fileConvert.dir/build.make CMakeFiles/fileConvert.dir/fileConvert.cpp.o
.PHONY : fileConvert.cpp.o

fileConvert.i: fileConvert.cpp.i
.PHONY : fileConvert.i

# target to preprocess a source file
fileConvert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fileConvert.dir/build.make CMakeFiles/fileConvert.dir/fileConvert.cpp.i
.PHONY : fileConvert.cpp.i

fileConvert.s: fileConvert.cpp.s
.PHONY : fileConvert.s

# target to generate assembly for a file
fileConvert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fileConvert.dir/build.make CMakeFiles/fileConvert.dir/fileConvert.cpp.s
.PHONY : fileConvert.cpp.s

gui.o: gui.cpp.o
.PHONY : gui.o

# target to build an object file
gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui.cpp.o
.PHONY : gui.cpp.o

gui.i: gui.cpp.i
.PHONY : gui.i

# target to preprocess a source file
gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui.cpp.i
.PHONY : gui.cpp.i

gui.s: gui.cpp.s
.PHONY : gui.s

# target to generate assembly for a file
gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui.cpp.s
.PHONY : gui.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... analysis"
	@echo "... dataContainer"
	@echo "... fileConvert"
	@echo "... gui"
	@echo "... main"
	@echo "... analysis.o"
	@echo "... analysis.i"
	@echo "... analysis.s"
	@echo "... dataContainer.o"
	@echo "... dataContainer.i"
	@echo "... dataContainer.s"
	@echo "... fileConvert.o"
	@echo "... fileConvert.i"
	@echo "... fileConvert.s"
	@echo "... gui.o"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

